/*
 * AUTO-GENERATED by scripts/generate_template.js — NIE EDYTUJ RĘCZNIE.
 * Zmiany geometrii: edytuj scripts/generate_template.js i uruchom go ponownie.
 */

export const OMR_PAGE = { W_MM: 210, H_MM: 297 } as const;

export const FIDUCIALS = {
  sideMm: 6,
  /** TL, TR, BL, BR */
  centersMm: [[8,8],[202,8],[8,289],[202,289]] as ReadonlyArray<readonly [number, number]>,
} as const;

export const SQUAD_GEOM = {
  bubbleRadiusMm: 2.5,
  yMm: 18.5,
  bubbleXMm: [48,57,66,75],
} as const;

export const ITEM_GEOM = {
  bubbleRadiusMm: 2.45,
  bubblePitchMm: 5.6,
  rowPitchMm: 7.6,
  timingWMm: 2.2,
  timingHMm: 2,
} as const;

export interface OmrRow {
  itemId: string;
  column: 1 | 2 | 3;
  yMm: number;
  bubbleXMm: number[];
  timingXMm: number;
}

export const OMR_ROWS: OmrRow[] = [
  {
    "itemId": "jablka",
    "column": 1,
    "yMm": 38.4,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "banany",
    "column": 1,
    "yMm": 46,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "nektarynka",
    "column": 1,
    "yMm": 53.6,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "arbuz",
    "column": 1,
    "yMm": 61.2,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "ziemniaki",
    "column": 1,
    "yMm": 76.4,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "cebula",
    "column": 1,
    "yMm": 84,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "marchew",
    "column": 1,
    "yMm": 91.6,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "pietruszka",
    "column": 1,
    "yMm": 99.2,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "pomidory",
    "column": 1,
    "yMm": 106.8,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "ogorki",
    "column": 1,
    "yMm": 114.4,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "papryka",
    "column": 1,
    "yMm": 122,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "czosnek",
    "column": 1,
    "yMm": 129.6,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "salata_mix",
    "column": 1,
    "yMm": 137.2,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "salata_glowka",
    "column": 1,
    "yMm": 144.8,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "pieczarki",
    "column": 1,
    "yMm": 152.4,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "brokuly",
    "column": 1,
    "yMm": 160,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "chleb",
    "column": 1,
    "yMm": 175.2,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "chleb_tostowy",
    "column": 1,
    "yMm": 182.8,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "bulki",
    "column": 1,
    "yMm": 190.4,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "tortilla",
    "column": 1,
    "yMm": 198,
    "bubbleXMm": [
      36.317,
      41.917,
      47.517,
      53.117,
      58.717
    ],
    "timingXMm": 9.7
  },
  {
    "itemId": "piers_z_kurczaka",
    "column": 2,
    "yMm": 38.4,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "mieso_mielone",
    "column": 2,
    "yMm": 46,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "schab",
    "column": 2,
    "yMm": 53.6,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "udka_z_kurczaka",
    "column": 2,
    "yMm": 61.2,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "skrzydelka_z_kurczaka",
    "column": 2,
    "yMm": 68.8,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "watrobka",
    "column": 2,
    "yMm": 76.4,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "boczek",
    "column": 2,
    "yMm": 84,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "parowki",
    "column": 2,
    "yMm": 99.2,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "szynka",
    "column": 2,
    "yMm": 106.8,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "kielbasa",
    "column": 2,
    "yMm": 114.4,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "mleko",
    "column": 2,
    "yMm": 129.6,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "maslo",
    "column": 2,
    "yMm": 137.2,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "jajka",
    "column": 2,
    "yMm": 144.8,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "ser_zolty_plasterki",
    "column": 2,
    "yMm": 152.4,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "ser_zolty_kostka",
    "column": 2,
    "yMm": 160,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "twarog",
    "column": 2,
    "yMm": 167.6,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "smietana_18",
    "column": 2,
    "yMm": 175.2,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "smietanka_30",
    "column": 2,
    "yMm": 182.8,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "jogurt_naturalny",
    "column": 2,
    "yMm": 190.4,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "serek_wiejski",
    "column": 2,
    "yMm": 198,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "jogurt_smakowe",
    "column": 2,
    "yMm": 205.6,
    "bubbleXMm": [
      101.983,
      107.583,
      113.183,
      118.783,
      124.383
    ],
    "timingXMm": 75.367
  },
  {
    "itemId": "maka_pszenna",
    "column": 3,
    "yMm": 38.4,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "cukier",
    "column": 3,
    "yMm": 46,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "makaron_swiderki",
    "column": 3,
    "yMm": 53.6,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "makaron_spaghetti",
    "column": 3,
    "yMm": 61.2,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "ryz",
    "column": 3,
    "yMm": 68.8,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "kasza_gryczana",
    "column": 3,
    "yMm": 76.4,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "kasza_jeczmienna",
    "column": 3,
    "yMm": 84,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "platki_owsiane",
    "column": 3,
    "yMm": 91.6,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "platki_na_mleko",
    "column": 3,
    "yMm": 99.2,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "bulka_tarta",
    "column": 3,
    "yMm": 106.8,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "olej",
    "column": 3,
    "yMm": 114.4,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "passata",
    "column": 3,
    "yMm": 129.6,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "groszek",
    "column": 3,
    "yMm": 137.2,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "kukurydza",
    "column": 3,
    "yMm": 144.8,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "tunczyk",
    "column": 3,
    "yMm": 152.4,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "fasola",
    "column": 3,
    "yMm": 160,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "ketchup",
    "column": 3,
    "yMm": 175.2,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "majonez",
    "column": 3,
    "yMm": 182.8,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "musztarda",
    "column": 3,
    "yMm": 190.4,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "sol",
    "column": 3,
    "yMm": 205.6,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "pieprz",
    "column": 3,
    "yMm": 213.2,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "papryka_slodka",
    "column": 3,
    "yMm": 220.8,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "papryka_ostra",
    "column": 3,
    "yMm": 228.4,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "czosnek_granulowany",
    "column": 3,
    "yMm": 236,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "ziola_prowansalskie",
    "column": 3,
    "yMm": 243.6,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "oregano",
    "column": 3,
    "yMm": 251.2,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  },
  {
    "itemId": "przyprawa_do_kurczaka",
    "column": 3,
    "yMm": 258.8,
    "bubbleXMm": [
      167.65,
      173.25,
      178.85,
      184.45,
      190.05
    ],
    "timingXMm": 141.033
  }
];

export const CATEGORY_ROWS: { name: string; column: 1 | 2 | 3; yMm: number; timingXMm: number }[] = [
  {
    "name": "Owoce",
    "column": 1,
    "yMm": 30.8,
    "timingXMm": 9.7
  },
  {
    "name": "Warzywa",
    "column": 1,
    "yMm": 68.8,
    "timingXMm": 9.7
  },
  {
    "name": "Pieczywo",
    "column": 1,
    "yMm": 167.6,
    "timingXMm": 9.7
  },
  {
    "name": "Mięso",
    "column": 2,
    "yMm": 30.8,
    "timingXMm": 75.367
  },
  {
    "name": "Wędliny",
    "column": 2,
    "yMm": 91.6,
    "timingXMm": 75.367
  },
  {
    "name": "Nabiał",
    "column": 2,
    "yMm": 122,
    "timingXMm": 75.367
  },
  {
    "name": "Produkty sypkie",
    "column": 3,
    "yMm": 30.8,
    "timingXMm": 141.033
  },
  {
    "name": "Konserwy",
    "column": 3,
    "yMm": 122,
    "timingXMm": 141.033
  },
  {
    "name": "Sosy",
    "column": 3,
    "yMm": 167.6,
    "timingXMm": 141.033
  },
  {
    "name": "Przyprawy",
    "column": 3,
    "yMm": 198,
    "timingXMm": 141.033
  }
];
